---
all:
  hosts:
    elastic-node-01:
      ansible_host: 51.250.42.131
    kibana-node-01:
      ansible_host: 51.250.42.131
    logstash-node-01:
      ansible_host: 51.250.42.131
    nexus-node-01:
      ansible_host: 51.250.42.131
  
  children:
    elk-stack:
      children:
        elastic:
          hosts:
            elastic-node-01:
        kibana:
          hosts:
            kibana-node-01:
        logstash:
          hosts:
            logstash-node-01:
    infrastructure:
          hosts:
            nexus-node-01:
      
  vars:
    ansible_connection_type: paramico
    ansible_user: dotsenkois
